version: '3.9'

services:
  setup:
    image: ddgu/fedservice
    entrypoint:
      - "python3"
      - "/app/setup.py"
      - "/conf"
    user: ${UID}:${GID}
    volumes:
      - ./conf:/conf
    profiles: [ 'setup' ]
  display:
    image: ddgu/fedservice
    entrypoint:
      - "python3"
      - "/app/display_entity.py"
    networks:
      - caddy
    profiles: [ 'cmd' ]
  lu:
    image: ddgu/fedservice
    init: true
    hostname: lu
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=intermediate
      - ENTITY_NAME=lu
    ports:
      - 6001:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/intermediate/lu:/conf
  umu:
    image: ddgu/fedservice
    init: true
    hostname: umu
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=intermediate
      - ENTITY_NAME=umu
    ports:
      - 6002:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/intermediate/umu:/conf
  swamid:
    image: ddgu/fedservice
    init: true
    hostname: swamid
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=ta
      - ENTITY_NAME=swamid
    ports:
      - 7002:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/ta/swamid:/conf
  seid:
    image: ddgu/fedservice
    init: true
    hostname: seid
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=ta
      - ENTITY_NAME=seid
    ports:
      - 7001:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/ta/seid:/conf
  auto:
    image: ddgu/fedservice
    init: true
    hostname: auto
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=rp
      - ENTITY_NAME=auto
    ports:
      - 4002:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/rp/auto:/conf
  expl:
    image: ddgu/fedservice
    init: true
    hostname: expl
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=rp
      - ENTITY_NAME=expl
    ports:
      - 4001:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/rp/expl:/conf
  op:
    image: ddgu/fedservice
    init: true
    hostname: op
    networks:
      - caddy
    environment:
      - ENTITY_TYPE=op
      - ENTITY_NAME=op
    ports:
      - 5000:80
    volumes:
      - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
      - ./conf/op/op:/conf
  # tm-personalized:
  #   image: ddgu/fedservice
  #   init: true
  #   hostname: tm-personalized
  #   networks:
  #     - caddy
  #   environment:
  #     - ENTITY_TYPE=intermediate
  #     - ENTITY_NAME=tm-personalized
  #   ports:
  #     - 6009:80
  #   volumes:
  #     - ./mkcertRootCA.crt:/usr/local/share/ca-certificates/mkcertRootCA.crt:ro
  #     - ./conf/tmi/tm-personalized:/conf
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    user: ${UID}:${GID}
    networks:
      caddy:
        aliases:
          - op.fedservice.lh
          - auto.fedservice.lh
          - expl.fedservice.lh
          - lu.fedservice.lh
          - umu.fedservice.lh
          - seid.fedservice.lh
          - swamid.fedservice.lh
          # - tm-personalized.fedservice.lh

networks:
  caddy:
    external: true
