services:
  setup:
    image: ddgu/fedservice
    entrypoint:
      - "python3"
      - "/app/setup.py"
      - "/conf"
    user: ${UID}:${GID}
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf:/conf
    profiles: [ 'setup' ]
  display:
    image: ddgu/fedservice
    entrypoint:
      - "bash"
      - "/app/display.sh"
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
    networks:
      - caddy
    profiles: [ 'cmd' ]
  ofcli:
    image: ddgu/ofcli
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
    networks:
      - caddy
    profiles: [ 'cmd' ]
  lu:
    image: ddgu/fedservice
    init: true
    hostname: lu
    networks:
      - caddy
    depends_on:
      caddy:
        condition: service_healthy
    environment:
      - ENTITY_TYPE=intermediate
      - ENTITY_NAME=lu
    ports:
      - 6001:80
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf/intermediate/lu:/conf
  umu:
    image: ddgu/fedservice
    init: true
    hostname: umu
    networks:
      - caddy
    depends_on:
      caddy:
        condition: service_healthy
    environment:
      - ENTITY_TYPE=intermediate
      - ENTITY_NAME=umu
    ports:
      - 6002:80
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf/intermediate/umu:/conf
  # swamid:
  #   image: ddgu/fedservice
  #   init: true
  #   hostname: swamid
  #   networks:
  #     - caddy
  #   depends_on:
  #     caddy:
  #       condition: service_healthy
  #   environment:
  #     - ENTITY_TYPE=ta
  #     - ENTITY_NAME=swamid
  #   ports:
  #     - 7002:80
  #   volumes:
  #     - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
  #     - ./conf/ta/swamid:/conf
  seid:
    image: ddgu/fedservice
    init: true
    hostname: seid
    networks:
      - caddy
    depends_on:
      caddy:
        condition: service_healthy
    environment:
      - ENTITY_TYPE=ta
      - ENTITY_NAME=seid
    ports:
      - 7001:80
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf/ta/seid:/conf
  auto:
    image: ddgu/fedservice
    init: true
    hostname: auto
    networks:
      - caddy
    depends_on:
      caddy:
        condition: service_healthy
    environment:
      - ENTITY_TYPE=rp
      - ENTITY_NAME=auto
    ports:
      - 4002:80
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf/rp/auto:/conf
  expl:
    image: ddgu/fedservice
    init: true
    hostname: expl
    networks:
      - caddy
    depends_on:
      caddy:
        condition: service_healthy
    environment:
      - ENTITY_TYPE=rp
      - ENTITY_NAME=expl
    ports:
      - 4001:80
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf/rp/expl:/conf
  op:
    image: ddgu/fedservice
    init: true
    hostname: op
    networks:
      - caddy
    depends_on:
      caddy:
        condition: service_healthy
    environment:
      - ENTITY_TYPE=op
      - ENTITY_NAME=op
    ports:
      - 5000:80
    volumes:
      - ./caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddyRootCA.crt:ro
      - ./conf/op/op:/conf
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    user: ${UID}:${GID}
    healthcheck:
      test: ["CMD-SHELL", "[ -f /data/caddy/pki/authorities/local/root.crt ]"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      caddy:
        aliases:
          - op.localhost
          - auto.localhost
          - expl.localhost
          - lu.localhost
          - umu.localhost
          - seid.localhost

networks:
  caddy:
    external: true
